"""The handbook renderer: grammar, derived presentation, determinism, drift.

The published handbook `docs/user-guide.html` is a build output of
`docs/USER-GUIDE.md`. These tests cover the renderer that produces it and the
check mode the verification workflow calls, so a regression in either is caught
by the same suite that already gates every change.

They also hold the equivalence check behind the reconciliation: the published
page as committed immediately before it became a build output, against the page
as regenerated at reconciliation time. Both are frozen fixtures, both are
normalised the same way, and every differing hunk must be recorded and
classified in `docs/user-guide-reconciliation-diff.md` against a row of the
reconciliation record. The check is hermetic on purpose: the reconciliation was
a one-time event, so its proof compares two frozen pages and stays true while
the handbook goes on being edited. The live page is exercised by the tests that
should stay live -- the banner, the anchor baseline, check mode writing nothing,
and the delivered page being a render of the delivered source -- and by the
record's own form checks. Nothing here writes to a tracked file.

How the reconciled fixture was produced. `tests/fixtures/user-guide-reconciled.html`
is a render of the handbook source as it stood when the reconciliation closed.
That source was reconstructed from the current `docs/USER-GUIDE.md` by returning
the four passages a later, separately delivered change had edited (the rework-loop
bullet on a rejected gate, the `Bounded rework` callout, the first-invocation
paragraph of `pr fix-comments`, and the two troubleshooting rows on a rejected gate
and on collected review comments) to the wording `HEAD:docs/USER-GUIDE.md` carries
for them, in the reconciled callout and link form. The reconstruction was checked
two ways before the render was frozen: its visible-text and element streams equal
the pre-change fixture's streams with every recorded hunk applied at its recorded
offset (zero hunks between the two), and the hunks recomputed between the
pre-change fixture and the render equal the recorded comparison entry by entry
(51 text hunks, 66 element hunks, same offsets, same segments). The render then
differed from the live page in exactly the five lines those four passages occupy.
"""

import difflib
import html as html_module
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

import render_user_guide as renderer  # noqa: E402

# The anchor identifier baseline the published handbook exposed before it became
# a build output. Every one must survive regeneration, and the internal link
# graph must stay closed over exactly this set.
BASELINE_ANCHORS = {
    "model", "install", "work", "flows", "run", "ownership", "health",
    "trouble", "custom",
    "flow-implement", "flow-bugfix", "flow-refactor", "flow-investigate",
    "flow-review", "flow-release", "flow-quality-scan",
    "rework", "fix-comments", "update", "run-e2e", "live-view",
}

# The published handbook as committed immediately before it became a build
# output (`git show HEAD:docs/user-guide.html` at the change's base), held as a
# fixture so the equivalence check below is hermetic and needs no `git`.
PRE_CHANGE_PAGE = REPO / "tests" / "fixtures" / "user-guide-pre-change.html"
# The page as regenerated from the reconciled source, frozen when the
# reconciliation closed (see the module docstring for how it was produced). The
# equivalence check compares the two fixtures, never the live page, so a later
# edit to the handbook is not read as an unrecorded reconciliation hunk.
RECONCILED_PAGE = REPO / "tests" / "fixtures" / "user-guide-reconciled.html"
PUBLISHED_PAGE = REPO / "docs" / "user-guide.html"
SOURCE = REPO / "docs" / "USER-GUIDE.md"
RECONCILIATION = REPO / "docs" / "user-guide-reconciliation.md"
COMPARISON = REPO / "docs" / "user-guide-reconciliation-diff.md"

MINIMAL = """# Handbook

*A strapline.*

An opening paragraph.

## 1. First chapter {#one}

A sentence.

## 2. Second chapter {#two}

A sentence with a [link](#one).

---

*A footer sentence.*
"""


def render(source):
    return renderer.render(source)


# --------------------------------------------------------------------------
# the normalised comparison
#
# Both fixtures are reduced to two streams. Inter-tag whitespace collapses, so
# the pre-change page's hand-wrapped paragraphs and the renderer's single-line
# ones read the same; attributes are dropped from the element stream except the
# class list, which is sorted. `docs/user-guide-reconciliation-diff.md` records
# every hunk these functions produce between the two fixtures, so it is
# regenerated by the same code that verifies it.
# --------------------------------------------------------------------------

_BLOCK_TAG = re.compile(
    r"</?(?:p|h1|h2|h3|h4|li|tr|pre|div|nav|header|footer|section|main|table"
    r"|ol|ul|title)\b[^>]*>", re.I)


def visible_text_stream(page):
    """The page's visible text, one segment per block-level element.

    Each paragraph, heading, list item, table row, navigation entry, callout
    tag and code line is one segment; the style block and the stylesheet link
    are not text. Entities are decoded so `&lt;` and `<` compare equal.
    """
    page = re.sub(r"<style>.*?</style>", "", page, flags=re.S)
    page = re.sub(r"<link\b[^>]*>", "", page)
    page = re.sub(r"<pre>.*?</pre>",
                  lambda match: match.group(0).replace("\n", "\x00"),
                  page, flags=re.S)
    page = page.replace("\r", "").replace("\n", " ").replace("\x00", "\n")
    page = re.sub(r"<(?:td|th)\b[^>]*>", " | ", page)
    page = re.sub(r'<a\b[^>]*><span class="n">[^<]*</span>', "\n", page)
    page = page.replace('<span class="tag">', "\n")
    page = _BLOCK_TAG.sub("\n", page)
    page = re.sub(r"<[^>]+>", "", page)
    segments = []
    for line in html_module.unescape(page).split("\n"):
        line = " ".join(line.split())
        if line:
            segments.append(line)
    return segments


def element_stream(page):
    """Every opening tag as `name.class.class`, classes sorted, style excluded."""
    page = re.sub(r"<style>.*?</style>", "", page, flags=re.S)
    out = []
    for match in re.finditer(r"<([A-Za-z][A-Za-z0-9]*)\b([^>]*)>", page):
        classes = re.search(r'class="([^"]*)"', match.group(2))
        suffix = ("." + ".".join(sorted(classes.group(1).split()))
                  if classes else "")
        out.append(match.group(1).lower() + suffix)
    return out


def hunks(before, after):
    """The differing runs between two streams as (at, before-run, after-run).

    `at` is the pair of 0-based offsets the run starts at in each stream.
    """
    matcher = difflib.SequenceMatcher(None, before, after, autojunk=False)
    return [((i1, j1), before[i1:i2], after[j1:j2])
            for op, i1, i2, j1, j2 in matcher.get_opcodes() if op != "equal"]


# The constructs the renderer holds or derives, which no record row names
# because they are not authored content. A hunk classified as one of these is
# intended-derived; anything else must cite a record row.
DERIVED_CONSTRUCTS = {
    "banner",          # the generated-file notice, emitted by the renderer
    "navigation",      # index entries regenerated from the chapter headings
    "chapter-label",   # the eyebrow "Chapter N" labels
    "table-marking",   # the numeric-table class, derived from the first column
    "nesting",         # section, table wrapper and callout wrapper elements
    "callout-shape",   # a one-paragraph callout emits no paragraph element
    "code-marking",    # comment spans, derived from the fence info string
    "chain-shape",     # the chain diagram's tokens and arrows
}

_ENTRY = re.compile(r"^### ([TE])-(\d+) · at (\d+)/(\d+) · (.*)$")


def parse_comparison(text):
    """Read the recorded comparison: per stream, its numbered hunk entries."""
    entries = {"T": [], "E": []}
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        match = _ENTRY.match(lines[index])
        index += 1
        if not match:
            continue
        tags = re.findall(r"`([^`]+)`", match.group(5))
        # an optional note paragraph may sit between the heading and the block
        while index < len(lines) and lines[index] != "```diff":
            if lines[index].startswith("### "):
                break
            index += 1
        if index >= len(lines) or lines[index] != "```diff":
            raise ValueError("entry %s-%s carries no diff block"
                             % (match.group(1), match.group(2)))
        index += 1
        minus, plus = [], []
        while lines[index] != "```":
            if lines[index].startswith("- "):
                minus.append(lines[index][2:])
            elif lines[index].startswith("+ "):
                plus.append(lines[index][2:])
            else:
                raise ValueError("entry %s-%s carries a line that is neither "
                                 "side: %r" % (match.group(1), match.group(2),
                                               lines[index]))
            index += 1
        entries[match.group(1)].append({
            "number": int(match.group(2)),
            "at": (int(match.group(3)), int(match.group(4))),
            "tags": tags, "minus": minus, "plus": plus,
        })
    return entries


def record_item_numbers(record):
    return {int(number) for number in re.findall(r"^\| (\d+) \|", record, re.M)}


def record_wording_labels(record):
    """The first cell of every row in the record's section 3."""
    section = record.split("\n## 3.", 1)[1].split("\n## ", 1)[0]
    labels = set()
    for line in section.splitlines():
        cells = [cell.strip() for cell in line.strip().split("|")[1:-1]]
        if len(cells) == 3 and cells[0] not in ("Section", "---"):
            labels.add(cells[0])
    return labels


def tree_snapshot(root):
    """Every file under `root`: its bytes and its modification time."""
    root = Path(root)
    return {str(path.relative_to(root)): (path.read_bytes(),
                                          path.stat().st_mtime_ns)
            for path in sorted(root.rglob("*")) if path.is_file()}


def files_snapshot(paths):
    return {str(path): (path.read_bytes(), path.stat().st_mtime_ns)
            for path in paths}


class Grammar(unittest.TestCase):
    def test_minimal_document_renders(self):
        html = render(MINIMAL)
        self.assertIn("<title>Handbook</title>", html)
        self.assertIn('<p class="kicker">A strapline.</p>', html)
        self.assertIn('<p class="lede">An opening paragraph.</p>', html)
        self.assertIn('<section id="one">', html)
        self.assertIn('<p class="eyebrow">Chapter 1</p>', html)
        self.assertIn("<footer>", html)
        self.assertIn("A footer sentence.", html)

    def test_navigation_is_derived_from_the_chapter_headings(self):
        html = render(MINIMAL)
        self.assertIn('<a href="#one"><span class="n">1</span>First chapter</a>',
                      html)
        self.assertIn('<a href="#two"><span class="n">2</span>Second chapter</a>',
                      html)

    def test_lettered_section_becomes_a_subsection_of_its_chapter(self):
        html = render(MINIMAL.replace(
            "## 2. Second chapter {#two}", "## 1a. A subsection {#two}"))
        self.assertIn('<h3 id="two">A subsection</h3>', html)
        # a lone capital is a word, not an enumerator: no separator is inserted
        self.assertNotIn("A · subsection", html)
        self.assertNotIn('<section id="two">', html)
        # a lettered section is not a chapter, so it takes no navigation entry
        self.assertNotIn('<span class="n">1</span>A subsection', html)

    def test_callout_tag_comes_from_the_leading_bolded_run(self):
        html = render(MINIMAL.replace(
            "A sentence.\n\n## 2.",
            "> **Watch out**\n> Body text.\n\n## 2.", 1))
        self.assertIn('<div class="callout">', html)
        self.assertIn('<span class="tag">Watch out</span>', html)
        self.assertIn("Body text.", html)

    def test_callout_variant_comes_from_the_brace_attribute(self):
        html = render(MINIMAL.replace(
            "A sentence.\n\n## 2.",
            "> **Yours** {.yours}\n> Body text.\n\n## 2.", 1))
        self.assertIn('<div class="callout yours">', html)

    def test_chain_fence_marks_its_gate_token(self):
        html = render(MINIMAL.replace(
            "A sentence.\n\n## 2.",
            "```chain\nalpha → **beta** → gamma\n```\n\n## 2.", 1))
        self.assertIn('<div class="chain" role="img"', html)
        self.assertIn("<span>alpha</span>", html)
        self.assertIn('<span class="gate">beta</span>', html)
        self.assertIn('aria-label="The chain: alpha to beta, then gamma"', html)

    def test_table_is_marked_numeric_only_when_its_first_column_is(self):
        numeric = render(MINIMAL.replace(
            "A sentence.\n\n## 2.",
            "| # | Phase |\n|---|---|\n| 1 | one |\n| 2 | two |\n\n## 2.", 1))
        self.assertIn('<div class="tbl"><table class="num">', numeric)
        textual = render(MINIMAL.replace(
            "A sentence.\n\n## 2.",
            "| Key | Phase |\n|---|---|\n| a | one |\n\n## 2.", 1))
        self.assertIn('<div class="tbl"><table>', textual)
        self.assertNotIn('table class="num"', textual)

    def test_steps_class_is_carried_by_a_standalone_attribute_line(self):
        html = render(MINIMAL.replace(
            "A sentence.\n\n## 2.",
            "{.steps}\n1. first\n2. second\n\n## 2.", 1))
        self.assertIn('<ol class="steps">', html)
        self.assertIn("<li>first</li>", html)

    def test_ordered_and_unordered_lists_follow_the_source_form(self):
        self.assertIn("<ol>", render(MINIMAL.replace(
            "A sentence.\n\n## 2.", "1. only\n\n## 2.", 1)))
        self.assertIn("<ul>", render(MINIMAL.replace(
            "A sentence.\n\n## 2.", "- only\n\n## 2.", 1)))

    def test_level_three_enumerator_is_set_off_from_its_title(self):
        html = render(MINIMAL.replace(
            "A sentence.\n\n## 2.", "### 1.1 A titled step\n\n## 2.", 1))
        self.assertIn("<h3>1.1 · A titled step</h3>", html)

    def test_inline_constructs_and_escaping(self):
        html = render(MINIMAL.replace(
            "A sentence.", "**bold** *slant* `a < b` plain & <raw>", 1))
        self.assertIn("<strong>bold</strong>", html)
        self.assertIn("<em>slant</em>", html)
        self.assertIn("<code>a &lt; b</code>", html)
        self.assertIn("plain &amp; &lt;raw&gt;", html)


class CommentMarking(unittest.TestCase):
    def mark(self, line, marker):
        return renderer.mark_comments(line, marker)

    def test_comment_at_line_start_is_marked(self):
        self.assertEqual(self.mark("# note", "#"),
                         '<span class="comment"># note</span>')

    def test_trailing_comment_is_marked_and_the_command_is_not(self):
        marked = self.mark("run --now   # why", "#")
        self.assertTrue(marked.startswith("run --now   "))
        self.assertIn('<span class="comment"># why</span>', marked)

    def test_marker_inside_a_quoted_run_is_not_a_comment(self):
        line = "scan --context 'sweep for PR #42' --approve"
        self.assertNotIn("comment", self.mark(line, "#"))

    def test_marker_not_preceded_by_whitespace_is_not_a_comment(self):
        self.assertNotIn("comment", self.mark("colour=#FAFBF9", "#"))

    def test_marker_depends_on_the_fence_info_string(self):
        self.assertNotIn("comment", self.mark("// note", "#"))
        self.assertIn("comment", self.mark("// note", "//"))

    def test_a_fence_with_no_known_info_string_marks_nothing(self):
        html = render(MINIMAL.replace(
            "A sentence.\n\n## 2.", "```\n# not a comment here\n```\n\n## 2.", 1))
        self.assertNotIn('class="comment"', html)


class GrammarFailures(unittest.TestCase):
    def assert_rejects(self, source, fragment, line=None):
        with self.assertRaises(renderer.SourceError) as caught:
            render(source)
        message = str(caught.exception)
        self.assertIn(fragment, message)
        if line is not None:
            self.assertTrue(
                message.startswith("%s:%d: " % (renderer.SOURCE_REL, line)),
                "the failure does not name source line %d: %s" % (line, message))
        return message

    def test_duplicate_anchor_identifier_fails_the_render(self):
        self.assert_rejects(
            MINIMAL.replace("{#two}", "{#one}"), "duplicate anchor identifier")

    def test_internal_link_to_an_undeclared_anchor_fails_the_render(self):
        self.assert_rejects(
            MINIMAL.replace("(#one)", "(#nowhere)"),
            "internal link to an undeclared anchor")

    def test_chapter_without_an_anchor_fails_the_render_naming_the_line(self):
        self.assert_rejects(
            MINIMAL.replace(" {#one}", ""), "declares no anchor", line=7)

    def test_callout_without_a_bolded_tag_fails_the_render(self):
        self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.", "> just prose\n\n## 2.", 1),
            "bolded tag alone", line=9)

    def test_content_after_the_closing_break_fails_the_render(self):
        self.assert_rejects(
            MINIMAL + "\nAn orphaned sentence.\n",
            "followed by the footer sentence and nothing else")

    def test_unterminated_fence_fails_the_render(self):
        self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.", "```bash\nrun\n\n## 2.", 1),
            "unterminated fenced block", line=9)

    # An unrecognised heading is a grammar failure, never paragraph prose: a
    # mis-authored heading must not reach the published page as literal text.

    def test_a_level_two_heading_without_an_ordinal_fails_naming_its_line(self):
        message = self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.",
                            "## Appendix\n\nA sentence.\n\n## 2.", 1),
            "a heading the grammar does not recognise", line=9)
        self.assertIn("## Appendix", message)

    def test_a_level_four_heading_fails_naming_its_line(self):
        message = self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.",
                            "#### Deep\n\nA sentence.\n\n## 2.", 1),
            "a heading the grammar does not recognise", line=9)
        self.assertIn("#### Deep", message)

    def test_a_second_title_heading_fails_naming_its_line(self):
        self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.",
                            "# Another title\n\nA sentence.\n\n## 2.", 1),
            "a heading the grammar does not recognise", line=9)

    def test_a_heading_inside_a_callout_fails_naming_its_line(self):
        self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.",
                            "> **Tag**\n> ## Inside\n\n## 2.", 1),
            "a heading the grammar does not recognise", line=10)

    def test_a_hash_that_opens_no_heading_is_still_prose(self):
        html = render(MINIMAL.replace("A sentence.", "#42 is the ticket.", 1))
        self.assertIn("<p>#42 is the ticket.</p>", html)


class AttributeSafety(unittest.TestCase):
    """A value in attribute position is encoded for that context or rejected.

    Element-content escaping leaves the quote intact; placed inside a quoted
    attribute it would close the attribute early. Derived labels are encoded;
    identifiers, which the grammar owns, are rejected at the source line.
    """

    def test_escape_attribute_encodes_the_quote_delimiter(self):
        self.assertEqual(renderer.escape_attribute('a "b" & <c>'),
                         "a &quot;b&quot; &amp; &lt;c&gt;")
        # element content keeps its quotes: only the attribute form encodes them
        self.assertEqual(renderer.escape('a "b"'), 'a "b"')

    def test_a_chain_token_with_a_quote_yields_a_well_formed_label(self):
        html = render(MINIMAL.replace(
            "A sentence.\n\n## 2.",
            '```chain\nsay "hi" → **gate**\n```\n\n## 2.', 1))
        opening = re.search(r'<div class="chain"[^>]*>', html).group(0)
        self.assertEqual(
            opening,
            '<div class="chain" role="img" '
            'aria-label="The chain: say &quot;hi&quot;, then gate">')
        self.assertIn('<span>say "hi"</span>', html)

    def assert_rejects(self, source, fragment, line):
        with self.assertRaises(renderer.SourceError) as caught:
            render(source)
        message = str(caught.exception)
        self.assertIn(fragment, message)
        self.assertTrue(
            message.startswith("%s:%d: " % (renderer.SOURCE_REL, line)),
            "the failure does not name source line %d: %s" % (line, message))

    def test_a_quote_in_an_anchor_identifier_fails_naming_its_line(self):
        # before this rule the tokenizer truncated `{#tw"o}` to `id="tw"`
        self.assert_rejects(MINIMAL.replace("{#two}", '{#tw"o}'),
                            "may not contain a double quote", line=11)

    def test_an_identifier_outside_its_alphabet_fails_naming_its_line(self):
        for bad in ("tw<o", "tw'o", "tw/o", "tw&o"):
            self.assert_rejects(MINIMAL.replace("{#two}", "{#%s}" % bad),
                                "an anchor identifier must match", line=11)

    def test_a_stray_token_in_the_braces_fails_rather_than_truncating(self):
        # `{#tw o}` would otherwise read as `id="tw"` with `o` ignored
        self.assert_rejects(MINIMAL.replace("{#two}", "{#tw o}"),
                            "unrecognised brace attribute token", line=11)

    def test_a_quote_in_a_class_name_fails_naming_its_line(self):
        self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.",
                            '{.st"eps}\n1. first\n\n## 2.', 1),
            "may not contain a double quote", line=9)
        self.assert_rejects(
            MINIMAL.replace("A sentence.\n\n## 2.",
                            "> **Yours** {.you<rs}\n> Body.\n\n## 2.", 1),
            "a class name must match", line=9)

    def test_every_attribute_value_in_the_published_page_is_well_formed(self):
        html = PUBLISHED_PAGE.read_text(encoding="utf-8")
        for tag in re.findall(r"<[a-z][^>]*>", html):
            # every attribute is name="value" with no raw quote inside
            self.assertNotRegex(tag, r'="[^"]*"[^\s>=/]',
                                "malformed attribute in %s" % tag)


class Determinism(unittest.TestCase):
    def test_two_renders_of_the_same_source_are_byte_identical(self):
        source = renderer.read_source()
        self.assertEqual(render(source).encode("utf-8"),
                         render(source).encode("utf-8"))

    def test_input_newline_form_does_not_reach_the_output(self):
        source = renderer.read_source()
        crlf = source.replace("\n", "\r\n")
        self.assertEqual(render(source), render(crlf))

    def test_the_output_carries_no_carriage_return(self):
        self.assertNotIn("\r", render(renderer.read_source()))

    def test_no_environment_value_reaches_the_output(self):
        html = render(renderer.read_source())
        self.assertNotIn(str(REPO), html)
        self.assertNotIn(os.sep + "docs" + os.sep, html)
        self.assertNotIn(sys.version.split()[0], html)


class PublishedHandbook(unittest.TestCase):
    """The committed published file is what a render of the source produces."""

    def setUp(self):
        self.html = PUBLISHED_PAGE.read_text(encoding="utf-8")

    def test_committed_output_matches_a_render_of_the_source(self):
        self.assertEqual(self.html, render(renderer.read_source()))

    def test_every_baseline_anchor_survives(self):
        declared = set(re.findall(r'\sid="([^"]+)"', self.html))
        self.assertEqual(declared, BASELINE_ANCHORS)

    def test_the_internal_link_graph_is_closed_over_the_baseline(self):
        targets = set(re.findall(r'href="#([^"]+)"', self.html))
        self.assertEqual(targets, BASELINE_ANCHORS)

    def test_the_page_opens_with_a_generated_do_not_edit_banner(self):
        head = self.html.split("<header>")[0]
        self.assertIn('class="banner"', head)
        self.assertIn("do not edit", head)
        self.assertIn("docs/USER-GUIDE.md", head)
        self.assertIn(renderer.RENDER_COMMAND, head)

    def test_the_named_reading_affordances_are_present(self):
        for fragment in ('<nav aria-label="Contents">', 'class="eyebrow"',
                         'class="callout"', 'class="chain"', 'class="comment"'):
            self.assertIn(fragment, self.html)

    def test_the_branch_naming_templates_section_reaches_the_published_form(self):
        for fragment in ("Branch naming templates", "Token reference",
                         "{ticket_id}", "Normalization and validation rules",
                         "Viewing and changing templates later",
                         "Migration and backward compatibility"):
            self.assertIn(fragment, self.html)

    def test_the_regeneration_command_uses_forward_slashes_only(self):
        self.assertNotIn("\\", renderer.RENDER_COMMAND)
        self.assertIn("tools/render_user_guide.py", renderer.RENDER_COMMAND)


class PreChangeEquivalence(unittest.TestCase):
    """The reconciled page is equivalent to the pre-change published page.

    Equivalent means: the same 21 anchors, and a visible-text stream and an
    element-and-class sequence that differ only where a recorded, classified
    hunk accounts for the difference. The hunks are computed here from the two
    frozen fixtures — the pre-change page and the page as regenerated when the
    reconciliation closed — and the recorded comparison must carry every one of
    them, in order, with a classification that cites a row of the
    reconciliation record, an ordering rule, or a construct the renderer
    derives. An authored segment that went missing with no record — the
    finding this class exists to catch — would surface as an unrecorded hunk.

    The live page is deliberately not a side of this comparison. "No content
    in exactly one file after reconciliation" is a statement about one event;
    comparing the live page here would turn it into a freeze of the handbook,
    failing every later legitimate edit until the record was amended.
    """

    @classmethod
    def setUpClass(cls):
        cls.before = PRE_CHANGE_PAGE.read_text(encoding="utf-8")
        cls.after = RECONCILED_PAGE.read_text(encoding="utf-8")
        cls.record = RECONCILIATION.read_text(encoding="utf-8")
        cls.comparison = parse_comparison(COMPARISON.read_text(encoding="utf-8"))
        cls.items = record_item_numbers(cls.record)
        cls.wording = record_wording_labels(cls.record)

    def test_the_fixture_is_the_pre_change_page(self):
        self.assertIn("Omn-Agent AI Engineering Framework · Team Guide",
                      self.before)
        self.assertIn("This guide is versioned at", self.before)
        self.assertNotIn('class="banner"', self.before)
        self.assertNotIn("Branch naming templates", self.before)

    def test_the_reconciled_fixture_is_a_render_of_the_reconciled_source(self):
        # a renderer output: it opens with the banner naming the source and the
        # regeneration command, and carries what the reconciliation merged in
        # from each side (the source's 5b section, the published 5a lines)
        head = self.after.split("<header>")[0]
        self.assertIn('class="banner"', head)
        self.assertIn("docs/USER-GUIDE.md", head)
        self.assertIn(renderer.RENDER_COMMAND, head)
        self.assertIn("Branch naming templates", self.after)
        self.assertNotIn("\r", self.after)
        # the two fixtures are distinct pages, not one file held twice
        self.assertNotEqual(self.before, self.after)

    def test_the_anchor_sets_of_both_pages_are_the_baseline(self):
        for page in (self.before, self.after):
            self.assertEqual(set(re.findall(r'\sid="([^"]+)"', page)),
                             BASELINE_ANCHORS)
            self.assertEqual(set(re.findall(r'href="#([^"]+)"', page)),
                             BASELINE_ANCHORS)

    def test_the_5a_command_lines_the_pre_change_page_carried_survive(self):
        # the Review Gate's finding: two authored command lines of the 5a
        # sample had been dropped; the reconciled page carries them as written
        before, after = (visible_text_stream(self.before),
                         visible_text_stream(self.after))
        for command in ("omn-agent pr fix-comments PROJ-42 -t ./my-repo",
                        "omn-agent update PROJ-42 -t ./my-repo"):
            in_before = [s for s in before if s.startswith(command + " #")]
            in_after = [s for s in after if s.startswith(command + " #")]
            self.assertEqual(len(in_before), 1, command)
            self.assertEqual(in_after, in_before,
                             "%s was dropped or reworded" % command)

    def assert_classified(self, kind, entry):
        label = "%s-%02d" % (kind, entry["number"])
        self.assertTrue(entry["tags"], "%s is unclassified" % label)
        for tag in entry["tags"]:
            if tag == "ordering":
                self.assertIn("## 4. Ordering", self.record)
            elif tag.startswith("item "):
                self.assertIn(int(tag[5:]), self.items,
                              "%s cites a record row that does not exist: %s"
                              % (label, tag))
            elif tag.startswith("wording: "):
                self.assertIn(tag[9:], self.wording,
                              "%s cites a section-3 row that does not exist: %s"
                              % (label, tag))
            elif tag.startswith("derived: "):
                self.assertIn(tag[9:], DERIVED_CONSTRUCTS,
                              "%s names an unknown derived construct: %s"
                              % (label, tag))
            else:
                # `defect`, `unclassified`, or anything the grammar lacks
                self.fail("%s is classified %r; a hunk is intended-derived, "
                          "accounted for by a record row, or a defect to fix"
                          % (label, tag))

    def assert_recorded(self, kind, stream):
        computed = hunks(stream(self.before), stream(self.after))
        recorded = self.comparison[kind]
        self.assertEqual(
            len(recorded), len(computed),
            "the recorded comparison carries %d %s hunks; the pages differ in "
            "%d" % (len(recorded), kind, len(computed)))
        for number, ((at, minus, plus), entry) in enumerate(
                zip(computed, recorded), 1):
            label = "%s-%02d" % (kind, number)
            self.assertEqual(entry["number"], number, label)
            self.assertEqual(entry["at"], at, "%s is recorded at the wrong "
                             "offsets" % label)
            self.assertEqual(entry["minus"], minus,
                             "%s: the pre-change side differs" % label)
            self.assertEqual(entry["plus"], plus,
                             "%s: the regenerated side differs" % label)
            self.assert_classified(kind, entry)

    def test_every_visible_text_hunk_is_recorded_and_classified(self):
        self.assert_recorded("T", visible_text_stream)

    def test_every_element_sequence_hunk_is_recorded_and_classified(self):
        self.assert_recorded("E", element_stream)

    def test_every_published_only_drop_is_reached_by_a_hunk(self):
        # a section-1 row resolved as dropped names published content that is
        # gone from the regenerated page, so some hunk must cite that row; a
        # chain's accessibility label, being an attribute, is cited on the
        # hunk carrying the chain itself
        cited = set()
        for entries in self.comparison.values():
            for entry in entries:
                for tag in entry["tags"]:
                    if tag.startswith("item "):
                        cited.add(int(tag[5:]))
        section_one = self.record.split("\n## 1.", 1)[1].split("\n## 2.", 1)[0]
        dropped = re.findall(r"^\| (\d+) \|.*\| dropped — ", section_one, re.M)
        self.assertTrue(dropped, "section 1 records no drop at all")
        for row in dropped:
            self.assertIn(int(row), cited,
                          "record item %s is resolved as dropped but no hunk "
                          "cites it" % row)


class CheckMode(unittest.TestCase):
    """Check mode compares in memory, reports a runnable fix, writes nothing.

    The failing outcomes run against an isolated copy of the handbook pair in
    a temporary directory, through the renderer's `--root` parameter. No test
    here writes to a tracked file, so a concurrent reader of the working tree
    never observes a mutated handbook and an interrupted run leaves nothing
    behind; every test also asserts that the tracked pair is untouched.
    """

    TRACKED = ("docs/USER-GUIDE.md", "docs/user-guide.html")

    def setUp(self):
        scratch = tempfile.TemporaryDirectory()
        self.addCleanup(scratch.cleanup)
        self.root = Path(scratch.name)
        (self.root / "docs").mkdir()
        for rel in self.TRACKED:
            shutil.copyfile(REPO / rel, self.root / rel)
        self.tracked_before = files_snapshot([REPO / rel
                                              for rel in self.TRACKED])

    def assert_tracked_untouched(self):
        self.assertEqual(files_snapshot([REPO / rel for rel in self.TRACKED]),
                         self.tracked_before,
                         "a check-mode test touched a tracked handbook file")

    def run_tool(self, *args, root=None):
        command = [sys.executable, str(REPO / "tools" / "render_user_guide.py")]
        command += list(args)
        if root is not None:
            command += ["--root", str(root)]
        return subprocess.run(command, capture_output=True, text=True,
                              cwd=str(REPO))

    def test_agreeing_pair_exits_zero(self):
        self.assertEqual(self.run_tool("--check").returncode, 0)
        self.assert_tracked_untouched()

    def test_an_agreeing_isolated_copy_exits_zero(self):
        before = tree_snapshot(self.root)
        self.assertEqual(self.run_tool("--check", root=self.root).returncode, 0)
        self.assertEqual(tree_snapshot(self.root), before)
        self.assert_tracked_untouched()

    def test_check_writes_nothing(self):
        path = PUBLISHED_PAGE
        before = path.read_bytes()
        stat = path.stat().st_mtime_ns
        self.run_tool("--check")
        self.assertEqual(path.read_bytes(), before)
        self.assertEqual(path.stat().st_mtime_ns, stat)
        self.assert_tracked_untouched()

    def test_mismatch_exits_nonzero_and_prints_the_regeneration_command(self):
        output = self.root / "docs" / "user-guide.html"
        with io.open(output, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(renderer.render(renderer.read_source(self.root))
                         + "<p>stale</p>\n")
        before = tree_snapshot(self.root)
        result = self.run_tool("--check", root=self.root)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("DRIFT", result.stdout)
        self.assertIn(renderer.RENDER_COMMAND, result.stdout)
        # the whole isolated tree, source included, is byte-for-byte and
        # mtime unchanged: check mode neither repairs nor touches anything
        self.assertEqual(tree_snapshot(self.root), before)
        self.assertEqual(output.read_bytes().decode("utf-8").count("<p>stale"),
                         1, "check mode must not repair the output")
        self.assert_tracked_untouched()

    def test_a_source_only_change_is_reported_as_drift(self):
        source = self.root / "docs" / "USER-GUIDE.md"
        edited = source.read_text(encoding="utf-8").replace(
            "## 9. Customizing",
            "A sentence added to the source only.\n\n## 9. Customizing", 1)
        with io.open(source, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(edited)
        before = tree_snapshot(self.root)
        result = self.run_tool("--check", root=self.root)
        self.assertEqual(result.returncode, 1,
                         "a source-only edit must read as drift, not as a "
                         "grammar failure: " + result.stdout)
        self.assertIn("DRIFT", result.stdout)
        self.assertIn(renderer.RENDER_COMMAND, result.stdout)
        self.assertEqual(tree_snapshot(self.root), before)
        self.assert_tracked_untouched()

    def test_a_missing_output_is_reported_as_the_strongest_staleness(self):
        (self.root / "docs" / "user-guide.html").unlink()
        before = tree_snapshot(self.root)
        html = renderer.render(renderer.read_source(self.root))
        self.assertEqual(renderer.check(html, self.root), 1)
        result = self.run_tool("--check", root=self.root)
        self.assertEqual(result.returncode, 1)
        self.assertIn("missing", result.stdout)
        self.assertIn(renderer.RENDER_COMMAND, result.stdout)
        self.assertEqual(tree_snapshot(self.root), before,
                         "a missing output must not be created by check mode")
        self.assert_tracked_untouched()

    def test_a_grammar_failure_exits_two_and_writes_nothing(self):
        source = self.root / "docs" / "USER-GUIDE.md"
        edited = source.read_text(encoding="utf-8").replace(
            "## 9. Customizing", "## Appendix\n\n## 9. Customizing", 1)
        with io.open(source, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(edited)
        before = tree_snapshot(self.root)
        result = self.run_tool("--check", root=self.root)
        self.assertEqual(result.returncode, 2, result.stdout)
        self.assertIn("ERROR: docs/USER-GUIDE.md:", result.stdout)
        self.assertIn("does not recognise", result.stdout)
        self.assertEqual(tree_snapshot(self.root), before)
        self.assert_tracked_untouched()

    def test_render_mode_with_a_root_writes_only_that_root(self):
        output = self.root / "docs" / "user-guide.html"
        output.unlink()
        result = self.run_tool(root=self.root)
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertEqual(output.read_bytes(), PUBLISHED_PAGE.read_bytes())
        self.assert_tracked_untouched()


class ReconciliationRecord(unittest.TestCase):
    """`docs/user-guide-reconciliation.md` is the reviewable record of the
    one-time two-way reconciliation: every item of authored content that lived
    in exactly one of the two files, with its resolution and the rule behind it.
    A row left unresolved, or resolved without naming a rule, would make the
    record unreviewable, which is the failure it exists to prevent. Its
    completeness against the pre-change page is executed by
    `PreChangeEquivalence`; this class checks the record's form."""

    PATH = RECONCILIATION

    def setUp(self):
        self.text = self.PATH.read_text(encoding="utf-8")
        self.rows = [line for line in self.text.splitlines()
                     if re.match(r"^\| \d+ \|", line)]

    @staticmethod
    def cells(row):
        return [cell.strip()
                for cell in re.split(r"(?<!\\)\|", row.strip())[1:-1]]

    def test_every_item_carries_a_resolution_and_a_rule_clause(self):
        self.assertGreater(len(self.rows), 30, "the record looks truncated")
        for row in self.rows:
            cells = self.cells(row)
            self.assertEqual(len(cells), 5, row)
            self.assertTrue(cells[3], "item left unresolved: " + row)
            self.assertRegex(cells[4], r"`R\d`", "no rule clause: " + row)

    def test_item_numbers_ascend_from_one_without_gaps(self):
        numbers = [int(self.cells(row)[0]) for row in self.rows]
        self.assertEqual(numbers, list(range(1, len(numbers) + 1)))

    def test_every_rule_it_cites_is_defined_in_its_rule_table(self):
        defined = set(re.findall(r"^\| `(R\d)` \|", self.text, re.M))
        cited = set(re.findall(r"`(R\d)`", self.text))
        self.assertEqual(cited - defined, set())
        self.assertEqual(defined - cited, set(), "a rule is defined but unused")

    def test_the_non_droppable_items_it_names_survive_in_both_files(self):
        html = PUBLISHED_PAGE.read_text(encoding="utf-8")
        source = SOURCE.read_text(encoding="utf-8")
        self.assertIn("non-droppable-merge", self.text)
        for fragment in ("pyyaml", "V-IMPORT"):
            self.assertIn(fragment, self.text)
            self.assertIn(fragment.lower(), html.lower())
            self.assertIn(fragment.lower(), source.lower())

    def test_the_5a_command_lines_carry_a_resolution_row(self):
        rows = "\n".join(self.rows)
        for command in ("omn-agent pr fix-comments PROJ-42 -t ./my-repo",
                        "omn-agent update PROJ-42 -t ./my-repo"):
            self.assertIn(command, rows, "no record row for " + command)

    def test_the_source_only_lead_in_sentences_carry_a_resolution_row(self):
        rows = "\n".join(self.rows)
        for sentence in ("The ticket-driven sequence, end to end:",
                         "The full chain from ticket to review is:"):
            self.assertIn(sentence, rows, "no record row for " + sentence)

    def test_no_dropped_item_is_left_unratified(self):
        # every drop of published wording is either ratified by its owner or
        # explicitly recorded as escalated, never applied on the implementer's
        # own judgement
        for row in self.rows:
            resolution = self.cells(row)[3]
            if resolution.startswith("dropped"):
                self.assertRegex(resolution, r"ratified|escalated",
                                 "a drop neither ratified nor escalated: " + row)

    def test_it_names_the_regeneration_and_check_commands(self):
        self.assertIn(renderer.RENDER_COMMAND, self.text)
        self.assertIn(renderer.CHECK_COMMAND, self.text)

    def test_it_names_the_recorded_comparison_and_both_fixtures(self):
        self.assertIn("docs/user-guide-reconciliation-diff.md", self.text)
        self.assertIn("tests/fixtures/user-guide-pre-change.html", self.text)
        self.assertIn("tests/fixtures/user-guide-reconciled.html", self.text)


class LineEndingPin(unittest.TestCase):
    """The byte comparison runs on both matrix legs, so the committed bytes of
    the handbook pair must reach a runner's disk untranslated."""

    def test_both_handbook_paths_are_pinned_against_translation(self):
        attributes = (REPO / ".gitattributes").read_text(encoding="utf-8")
        effective = [line for line in attributes.splitlines()
                     if line.strip() and not line.lstrip().startswith("#")]
        for path in ("docs/USER-GUIDE.md", "docs/user-guide.html"):
            matching = [line for line in effective if line.split()[0] == path]
            self.assertEqual(len(matching), 1, "%s is not pinned" % path)
            self.assertIn("-text", matching[0].split()[1:])


class WorkflowBinding(unittest.TestCase):
    def setUp(self):
        self.text = (REPO / ".github" / "workflows" / "verify.yml").read_text(
            encoding="utf-8")

    def test_the_drift_step_lives_in_the_tests_job(self):
        import yaml
        workflow = yaml.safe_load(self.text)
        steps = workflow["jobs"]["tests"]["steps"]
        runs = [step.get("run", "") for step in steps]
        self.assertTrue(any("render_user_guide.py --check" in run
                            for run in runs))
        self.assertLess(
            next(i for i, run in enumerate(runs) if "unittest discover" in run),
            next(i for i, run in enumerate(runs)
                 if "render_user_guide.py --check" in run),
            "the drift step reports after the suite, so both surfaces report")

    def test_the_drift_step_runs_unless_the_run_was_cancelled(self):
        import yaml
        workflow = yaml.safe_load(self.text)
        step = next(s for s in workflow["jobs"]["tests"]["steps"]
                    if "render_user_guide.py --check" in s.get("run", ""))
        self.assertEqual(step["if"], "${{ !cancelled() }}",
                         "always() would run the step after a cancellation")

    def test_the_step_names_one_build_output_not_a_file_list(self):
        self.assertEqual(self.text.count("render_user_guide.py --check"), 1)
        self.assertNotIn("docs/user-guide.html", self.text)


if __name__ == "__main__":
    unittest.main(verbosity=2)
